
import jwt, json
token = "eyJhbGciOiJIUzI1NiIsImtpZCI6Inlva1lOazNUSWYwc3BITjEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL29lbWxhY2N5eHN4bWhhd2d2emZnLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI4ZDI2MzJlNC0wNTUwLTQzMmUtODFkYi0zOGYwMDMwODRhMmQiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzY1NTI3MzQwLCJpYXQiOjE3NjU1MjM3NDAsImVtYWlsIjoiYXNpZi5zaGFrZWVsQGdtYWlsLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzY1NTIzNzQwfV0sInNlc3Npb25faWQiOiIyMTFiM2JhMi1kODBkLTRjN2MtODE2My0wYTljNGFiYjU3MmMiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.T7MK6ahUneyow2QPaeHQRV-BxO9PbiBbfVRPKchhBH8"
print(json.dumps(jwt.decode(token, options={"verify_signature": False}), indent=2))

